<?php
/**
 * Created by PhpStorm.
 * User: devert
 * Date: 3/17/20
 * Time: 1:17 PM
 */

namespace App\Http\Resources\Api\Business;


use Illuminate\Http\Resources\Json\Resource;

class PostpaidBillResource extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
